services:
  mongodb:
    image: mongo:8
    container_name: trackranker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - trackranker-mongodb-data:/data/db

volumes:
  trackranker-mongodb-data:
    name: trackranker-mongodb-data
